name: CI atlas 

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          repository: https://github.com/VikrantRuhela/atlas
          ref: master
          path: atlas
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: ./atlas
          config: exynos850-a21snsxx_defconfig
          arch: arm64
          aosp-clang: true
          anykernel3: true
